// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using project_renault;

#nullable disable

namespace project_renault.Migrations
{
    [DbContext(typeof(DBSettings))]
    [Migration("20240627232213_addAlertTime2")]
    partial class addAlertTime2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("project_renault.Models.RiskModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AreaResponsavel")
                        .HasColumnType("longtext");

                    b.Property<string>("ClassificacaoRisco")
                        .HasColumnType("longtext");

                    b.Property<string>("Consequencias")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataEntradaRisco")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DescricaoRisco")
                        .HasColumnType("longtext");

                    b.Property<string>("Impacto")
                        .HasColumnType("longtext");

                    b.Property<string>("ImpactoRenault")
                        .HasColumnType("longtext");

                    b.Property<string>("JalonAfetado")
                        .HasColumnType("longtext");

                    b.Property<string>("Metier")
                        .HasColumnType("longtext");

                    b.Property<string>("Probabilidade")
                        .HasColumnType("longtext");

                    b.Property<string>("Projeto")
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .HasColumnType("longtext");

                    b.Property<int>("id_solution")
                        .HasColumnType("int");

                    b.Property<int>("id_usuario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Risk");
                });

            modelBuilder.Entity("project_renault.Models.SolutionModel", b =>
                {
                    b.Property<int>("Id_Solution")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Solution"));

                    b.Property<string>("Acao")
                        .HasColumnType("longtext");

                    b.Property<bool>("Capitalizacao")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Comentario")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataAlerta")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Data_Resolucao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Estrategia")
                        .HasColumnType("longtext");

                    b.Property<int>("Id_Piloto")
                        .HasColumnType("int");

                    b.Property<string>("Impacto_Residual")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Inicio_Plano_De_Acao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome_Piloto")
                        .HasColumnType("longtext");

                    b.Property<float?>("Probabilidade_Residual")
                        .HasColumnType("float");

                    b.Property<string>("Validacao_Acao")
                        .HasColumnType("longtext");

                    b.Property<string>("Validacao_Risco")
                        .HasColumnType("longtext");

                    b.Property<int>("id_risk")
                        .HasColumnType("int");

                    b.HasKey("Id_Solution");

                    b.ToTable("Solution");
                });

            modelBuilder.Entity("project_renault.Models.UserModel", b =>
                {
                    b.Property<int>("id_usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_usuario"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("login")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("sessaoValida")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("id_usuario");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
