// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using project_renault;

#nullable disable

namespace project_renault.Migrations
{
    [DbContext(typeof(DBSettings))]
    [Migration("20240523193655_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("project_renault.Models.RiskModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AreaResponsavel")
                        .HasColumnType("longtext");

                    b.Property<string>("ClassificacaoRisco")
                        .HasColumnType("longtext");

                    b.Property<string>("Consequencias")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataEntradaRisco")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DescricaoRisco")
                        .HasColumnType("longtext");

                    b.Property<string>("Impacto")
                        .HasColumnType("longtext");

                    b.Property<string>("ImpactoRenault")
                        .HasColumnType("longtext");

                    b.Property<string>("JalonAfetado")
                        .HasColumnType("longtext");

                    b.Property<string>("Metier")
                        .HasColumnType("longtext");

                    b.Property<string>("Probabilidade")
                        .HasColumnType("longtext");

                    b.Property<string>("Projeto")
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Risk");
                });
#pragma warning restore 612, 618
        }
    }
}
